localization for principia(have some problem)
mockingbirdnest/Principia pull request #2857
Opened 2021-01-10 11:02 UTC by CindyRIng

Every thing is done except this problem that _**some strings are hidden**_.
![image](https://user-images.githubusercontent.com/67212205/104121016-4099ce00-5376-11eb-8160-7d8fce5432d8.png)

2021-01-10 11:03 UTC, pleroy commented
[Automated message from GitHub Pull Request Builder]  Answer "ok to test" to trigger testing of this PR.

2021-01-10 11:18 UTC, CindyRIng commented
ok to test

2021-01-10 20:19 UTC, eggrobin requested changes
Thank you very much for this significant contribution; this looks very good overall.

As I foretold I will have many comments about naming; let’s do this one window at a time, I commented on the strings referenced in `main_window.cs`, I will look at the other ones later.

I also took a quick look at the translations themselves, and I have a question about the best way to translate some of the more obscure technical terms we use.

2021-01-10 20:26 UTC, eggrobin commented on Localization/en-us.cfg
> +        #Principia_OBTAnalyser_Plugin_Recurrence = Recurrence: <<1>>; <<2>>; <<3>> //<<1>> nuo <<2>> dto <<3>> cto
Keep the square brackets here, including in the Chinese version. [ν<sub>o</sub>; D<sub>T<sub>o</sub></sub>; C<sub>T<sub>o</sub></sub>] is a notation from [[Cap12]](https://github.com/mockingbirdnest/Principia/blob/b9981c096b5539fc0025a059c3230821a45d7880/documentation/bibliography.pdf), with a specific technical meaning; this is not just three numbers separated by semicolons.

2021-01-11 01:18 UTC, eggrobin commented on ksp_plugin_adapter/main_window.cs
> +          Localizer.Format("#Principia_MainMenu_LogText_RecordjournalResault",
JournallingStatus.

2021-01-11 01:18 UTC, eggrobin commented on ksp_plugin_adapter/main_window.cs
> +                         Localizer.Format("#Principia_MainMenu_LogText_RecordjournalOFF"))),
JournallingStatus_ON/OFF.

2021-01-12 04:07 UTC, eggrobin commented on Localization/zh-cn.cfg
> +        #Principia_OBTAnalyser_Resault_AnomalisticPeriod = 近点平均周期
> this is indeed the mean anomalistic period

Actually on second thought « mean anomalistic period » feels wrong; there is only one kind of osculating period, as distinguishing the periods is something you can only do if you have some sort of perturbation theory—which largely amounts to having a mean element theory.

Let’s just use the names of the three kinds of periods without further qualification, thus
sidereal period: 恒星周期
anomalistic period: 近点周期
nodal period: 交点周期

2021-01-18 22:44 UTC, eggrobin requested changes
I have commented on all remaining identifiers; I will review the translations of technical terms once that is addressed.
Many of the technical translations need changes, but since the cfg file will completely change with the renamings, doing both at the same time would make it complicated to keep track of what has and hasn’t been done.

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +          $@"{Localizer.Format("#Principia_OBTAnalyser_StaticText_Recurrence")} [{
`Principia_OrbitAnalyser_Recurrence_CapderouTriple`; make the triple a placeholder (`Recurrence: <<1>>`), and rewrite the call as follows:
```csharp
      string νₒ = recurrence?.nuo.ToString() ?? em_dash;
      string Dᴛₒ = recurrence?.dto.ToString("+0;-0") ?? em_dash;
      string Cᴛₒ = recurrence?.cto.ToString() ?? em_dash;
      UnityEngine.GUILayout.Label(
          Localizer.Format("#Principia_OrbitAnalyser_Recurrence_CapderouTriple",
                           $"[{νₒ}; {Dᴛₒ}; {Cᴛₒ}]"),
          GUILayoutWidth(8));
```

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +          Localizer.Format("#Principia_OBTAnalyser_StaticText_AutoDetect"),
Principia_OrbitAnalyser_Recurrence_AutoDetect

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +      UnityEngine.GUILayout.Label(Localizer.Format("#Principia_OBTAnalyser_StaticText_Cycle"));
Principia_OrbitAnalyser_Recurrence_Cycle

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +      UnityEngine.GUILayout.Label(Localizer.Format("#Principia_OBTAnalyser_StaticText_Revolutions"),
Principia_OrbitAnalyser_Recurrence_Cycle_RevolutionsEquals

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
>                                    UnityEngine.GUILayout.ExpandWidth(false));
This needs to be translated too. Principia_OrbitAnalyser_Recurrence_Cycle_Days.

These are not days as in the 24-hour (or 6-hour on Kerbin) unit, which we write `d` or `d6`, a symbol which does not require translation.
These are « days » in a very strange technical sense, see https://github.com/mockingbirdnest/Principia/blob/15efd78a279d2504c30597b40d2bddd26fc9e06b/astronomy/orbit_recurrence.hpp#L29-L37.

It is best to use the word for « day » here ([[Cap12]](https://github.com/mockingbirdnest/Principia/blob/master/documentation/bibliography.pdf), which is in French, uses the word _jour_), thus here 天 in the zh-CN translation.

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +        Localizer.Format("#Principia_OBTAnalyser_Resault_Subcycle"),
Principia_OrbitAnalyser_Recurrence_Subcycle

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
>          $@"{recurrence?.subcycle.FormatN(0) ?? em_dash} days");
This also needs to be translated; `Principia_OrbitAnalyser_Recurrence_SubcycleLengthInDays`, `<<1>> days`, `<<1>> 天`.

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +        Localizer.Format("#Principia_OBTAnalyser_Resault_EquatorialShift"),
`Principia_OrbitAnalyser_Recurrence_EquatorialShift`

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +        Localizer.Format("#Principia_OBTAnalyser_Resault_GridInterval"),
`Principia_OrbitAnalyser_Recurrence_GridInterval`

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +          Localizer.Format("#Principia_OBTAnalyser_StaticText_REC"),
`Principia_OrbitAnalyser_GroundTrack_LongitudesOfEquatorialCrossings`

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +        Localizer.Format("#Principia_OBTAnalyser_Resault_AscendingPass"),
`Principia_OrbitAnalyser_GroundTrack_AscendingPass`

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +        Localizer.Format("#Principia_OBTAnalyser_Resault_DescendingPass"),
`Principia_OrbitAnalyser_GroundTrack_DescendingPass`

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +          label            : Localizer.Format("#Principia_OBTAnalyser_StaticText_Duration"),
Principia_OrbitAnalyser_MissionDuration

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +        ? Localizer.Format("#Principia_OBTAnalyser_ButtonOrbitAnalysis")
Principia_CurrentOrbitAnalyser_ToggleButton

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +        : Localizer.Format("#Principia_OBTAnalyser_ButtonAnalysis", orbit_description);
Principia_CurrentOrbitAnalyser_ToggleButtonWithDescription

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +    return Localizer.Format("#Principia_OBTAnalyser_ButtonAnalysisOBTOf", predicted_vessel.vesselName);
Principia_CurentOrbitAnalyser_Analysing

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +        ? Localizer.Format("#Principia_OBTAnalyser_ButtonAnalyseFinalTR")
Principia_PlannedOrbitAnalyser_ToggleButton

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +        : Localizer.Format("#Principia_OBTAnalyser_ButtonFinalOBTAnalysis", orbit_description);
Principia_PlannedOrbitAnalyser_ToggleButtonWithDescription

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/orbit_analyser.cs
> +    return Localizer.Format("#Principia_OBTAnalyser_ButtonAnalysisFinalPlanObt", predicted_vessel.vesselName);
Principia_PlannedOrbitAnalyser_Analysing

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/reference_frame_selector.cs
> +     return Localizer.Format("#Principia_RFS_DynamicTitle_Target", selected.NameWithArticle());
Principia_ReferenceFrameSelector_Name_Target

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/reference_frame_selector.cs
> +       return Localizer.Format("#Principia_RFS_DynamicTitle_XCI",
Principia_ReferenceFrameSelector_Name_BodyCentredNonRotating

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/reference_frame_selector.cs
> +          return Localizer.Format("#Principia_RFS_DynamicTitle_XYB",
Principia_ReferenceFrameSelector_Name_BarycentricRotating

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/reference_frame_selector.cs
> +          return Localizer.Format("#Principia_RFS_DynamicTitle_XCYA",
Principia_ReferenceFrameSelector_Name_BodyCentredParentDirection

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/reference_frame_selector.cs
> +       return Localizer.Format("#Principia_RFS_DynamicTitle_XCXF",
Principia_ReferenceFrameSelector_Name_BodySurface

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/reference_frame_selector.cs
> +      return Localizer.Format("#Principia_RFS_NavBallText_Target",
Principia_ReferenceFrameSelector_ShortName_Target, and same below in this function,
Principia_ReferenceFrameSelector_ShortName_BodyCentredNonRotating etc.

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/reference_frame_selector.cs
> +      return Localizer.Format("#Principia_RFS_DynamicText_Target",
Principia_ReferenceFrameSelector_Description_Target, and same below in this function, Principia_ReferenceFrameSelector_Description_BodyCentredNonRotating etc.

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/reference_frame_selector.cs
> +        ? Localizer.Format("#Principia_RFS_DynamicText_Sencondary")
Principia_ReferenceFrameSelector_ReferencePlane_Secondary_Target

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/reference_frame_selector.cs
> +    return Localizer.Format("#Principia_RFS_DynamicText_PlaneReturn",
Principia_ReferenceFrameSelector_ReferencePlane

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/reference_frame_selector.cs
> +        Localizer.Format("#Principia_RFS_Button",
Principia_ReferenceFrameSelector_ToggleButton

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/reference_frame_selector.cs
> +  protected override string Title =>Localizer.Format("#Principia_RFS_Title",
Principia_ReferenceFrameSelector_Title

2021-01-18 22:44 UTC, eggrobin commented on ksp_plugin_adapter/reference_frame_selector.cs
> +              Localizer.Format("#Principia_RFS_DynamicText_EnableTarget",
Principia_ReferenceFrameSelector_TargetFrameSelected

2021-01-31 13:48 UTC, pleroy commented
retest this please

2021-02-03 18:51 UTC, eggrobin approved these changes

2021-02-03 18:51 UTC, merged